apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: polyverse-ledger
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      containers:
      - image: gcr.io/polyverse-ledger/polyverse-ledger
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-url
              key: latest
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-anon-key
              key: latest
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 24  # 240 seconds total
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
